define([], function() {
   'use strict';

   var getTerrain = function() {
      var rows = [];
      rows[0]  = 'grass,       grass,        grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[1]  = 'stoneNgrass, grassSEstone, grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[2]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[3]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[4]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[5]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[6]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[7]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[8]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[9]  = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[10] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[11] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[12] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[13] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[14] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[15] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[16] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[17] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[18] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[19] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[20] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[21] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[22] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[23] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[24] = 'stone,       stoneEgrass,  grass,        grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');

      rows.forEach(function(row, rowIndex) {
         row.forEach(function(tile, columnIndex) {
            rows[rowIndex][columnIndex] = tile.trim();
         });
      });
      return rows;
   }
   return { getTerrain: getTerrain };
});