define([], function() {
   'use strict';

   var getTerrain = function() {
      var rows = [];
      rows[0]  = 'grass,             grass,              grassNEstone,grassNEstone, stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,    stoneEgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[1]  = 'grassSWstone,      grassSWstone,              grass,       grass, grassNEstone,   grassNEstone,   stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,          stone,   grassNWstone,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[2]  = 'stone,             stone,              grassSWstone,       grass, grass,          grass,    grassNEstone,   grassNEstone,         stone,          stone,          stone,          stone,          stone,          stone,   stoneEgrass,   grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[3]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,    stoneWgrass,          stone,          stone,          stone,          stone,    stoneSgrass,    stoneEgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[4]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,    stoneWgrass,          stone,          stone,    stoneSgrass,    stoneSgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[5]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,    stoneWgrass,    stoneSgrass,    stoneSgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[6]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,   grassNEstone,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[7]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[8]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,  grassSEforest,         forest , grassSWforest,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[9]  = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,   forestWgrass,         forest,   forestEgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[10] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,   forestWgrass,         forest,   forestEgrass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[11] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,  grassNEforest,          grass,  grassNWforest,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[12] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,           grass,         grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[13] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[14] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[15] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[16] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[17] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[18] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[19] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[20] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[21] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[22] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[23] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');
      rows[24] = 'stone,             stone,               stoneEgrass,       grass, grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass,          grass'.split(',');

      rows.forEach(function(row, rowIndex) {
         row.forEach(function(tile, columnIndex) {
            rows[rowIndex][columnIndex] = tile.trim();
         });
      });
      return rows;
   }
   return { getTerrain: getTerrain };
});